# Файл docker-compose.yml
version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    build: ./frontend/
    networks:
      - app-network
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
# Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
